name: placement_prediction_analysis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  webview_flutter: ^4.4.0
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.3
  fluttertoast: ^8.2.12
  webview_flutter_android: ^4.3.5
  webview_flutter_wkwebview: ^3.18.6
  flutter_inappwebview: ^6.1.5
  onnxruntime: ^1.4.1
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/infosys.png
    - assets/wipro.png
    - assets/ltimindtree.png
    - assets/techmahindra.png
    - assets/cognizant.png
    - assets/accenture.png


